services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mabase
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: monmotdepasse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./back
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://monuser:monmotdepasse@db:5432/mabase

  frontend:
    build: ./front
    command: npm run dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: